---
  - name: "create app directory"
    become: yes
    file:
      path: /home/ubuntu/backend
      state: directory
    
  - name: "Copy backend build folder to EC2"
    become: yes
    unarchive:
      src: artefacts.tar.gz
      dest: /home/ubuntu/backend/
      owner: ubuntu
      group: ubuntu
      mode: 0777 

  - name: "Copy package json"
    become: yes
    copy:
      src: package.json
      dest: /home/ubuntu/backend/
      owner: ubuntu
      group: ubuntu
      remote_src: yes
      mode: 0777
  
  - name: "Copy package json"
    become: yes
    copy:
      src: package.json
      dest: /home/ubuntu/backend/dist/
      remote_src: yes
      mode: 0777
      owner: ubuntu
      group: ubuntu

  - name: "install pm2"
    become: yes
    npm:
      name: pm2
      global: yes
      production: yes
      state: present

  - name: "start pm2"
    become: yes
    shell: | 
      cd /home/ubuntu/backend/dist
      pm2 start npm --name 'udapeople' -- start
      pm2 ls
      pm2 status
