Description: >
  UdaPeople backend stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub UdaPeople-${ID}
      GroupDescription: Allow port 22, 3030 and 9100.
      VpcId: vpc-00d91cfd25f3f2978
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: rsucprojkey 
      ImageId: ami-083654bd07b5da81d
      NetworkInterfaces: 
        - AssociatePublicIpAddress: Yes
          DeviceIndex: 0
          SubnetId: subnet-0b5515760ac49d340
          GroupSet:
            - Ref: InstanceSecurityGroup
 
      Tags:
        - Key: Name
          Value: !Sub udapeople-backend-${ID}
